# Práctica Clase 3

## Numpy

In [1]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [6]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
lista[2] = 0
arreglo[2]=0
print(lista[2:])
print(arreglo[2:])

[0, 3, 4, 5]
[0 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [9]:
arreglo = np.arange(8)
numeros = list(range(8))
impares = list(range(1, 50, 2))
print(arreglo)
print(numeros)
print(impares)

[0 1 2 3 4 5 6 7]
[0, 1, 2, 3, 4, 5, 6, 7]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [12]:
lista = [2,3,5,True, 'Hola']
nums = np.array([2,3,6,'Hola'])
nums

array(['2', '3', '6', 'Hola'], dtype='<U11')

Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [ ]:
lista + 1

In [17]:
nums = np.arange(9) 
nums +1 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arreglo = arreglo + 1

In [ ]:
arreglo

2. Elevar al cuadrado todos los elementos

In [18]:
nums**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [ ]:
arreglo**2

3. Sumar todos los elementos

In [21]:
print(nums.sum())
sum(numeros)

36


28

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

In [23]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [34]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [35]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [36]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [37]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [38]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

In [ ]:
a3 = a1 * a2
a3.shape

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [51]:
secuencia = np.arange(0,10)
secuencia


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
espaciados = np.linspace(0, 9, 100,)
espaciados
print(len(espaciados))

100


**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [58]:
enteros = np.arange(10, 101)
mask = enteros %3 == 0
enteros[mask]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [85]:
ceros = np.zeros((5,10))
ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
ceros[[1,4],:] = 1
ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
ceros[:, [3, 8]] = 5
ceros

array([[0., 0., 0., 5., 0., 0., 0., 0., 5., 0.],
       [1., 1., 1., 5., 1., 1., 1., 1., 5., 1.],
       [0., 0., 0., 5., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0., 5., 0.],
       [1., 1., 1., 5., 1., 1., 1., 1., 5., 1.]])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [ ]:
a = np.random.random((4,2,3)) * 100 + 100
a

In [ ]:
a = np.random.random((4,4))

In [ ]:
a

In [ ]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.std()

In [ ]:
a.sort(axis=1)

In [ ]:
a

In [ ]:
a.sort(axis=0)
a

In [ ]:
a[1:3,0:3]

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

In [ ]:
a.reshape(24)

In [ ]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

In [ ]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

In [ ]:
c = a * b 
print(c) 

In [ ]:
d = b * a 
print(d)