Módulo numpy

In [ ]:
lista = [3,5,9,0, True, 'Hola Mundo']
print(lista[2])

In [ ]:
matriz = [[1,2,3],
          [4,5,6],
          [7,8,9]]

numeros = [2,3,5]
matriz[1][2]

In [ ]:
import numpy as np

#np.array([2,3,45])
#np.array(numeros)
matriz_a = np.array(matriz)
a.shape

In [ ]:
secuencia = np.arange(19)
print(secuencia)

In [ ]:
secuencia[4]

In [ ]:
matriz_a[0][1]

In [ ]:
espacio = np.linspace(1.1, 4, 3)
print(espacio)

In [ ]:
nada = np.full((4,3), 7)
print(nada*4)

In [ ]:
azar = np.random.rand(4,3)
azar * 10

In [ ]:
serie = np.arange(16)
serie2 = np.resize(serie, [4,4,2])
serie2

In [ ]:
serie = np.arange(32).reshape([4,4,2])
#serie2 = np.reshape(serie, [4,4,2])
serie

Slicing

In [61]:
de9 = np.arange(9).reshape([3,3])
print(de9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [75]:
#print(de9[1,2])
#print(de9[:,1])
#print(de9[:2,:2])
de9 = np.arange(6).reshape([2,3])
#de9.T
numeros = np.arange(14)
mascara = ((numeros % 2) ==0)
mascara
numeros[mascara]

array([ 0,  2,  4,  6,  8, 10, 12])